import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Manually curated sidebar for helmpy documentation
  tutorialSidebar: [
    'index', // Homepage/Overview
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'installation',
        'quickstart',
        'usage',
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      link: {
        type: 'generated-index',
        title: 'Architecture Documentation',
        description: 'Detailed architecture documentation for helmpy',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'architecture',
        },
      ],
    },
    {
      type: 'category',
      label: 'Examples',
      link: {
        type: 'generated-index',
        title: 'Examples',
        description: 'Practical examples demonstrating helmpy usage',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'examples',
        },
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      link: {
        type: 'generated-index',
        title: 'API Documentation',
        description: 'Complete API reference for all helmpy classes and methods',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'api',
        },
      ],
    },
    {
      type: 'category',
      label: 'Support',
      items: [
        'troubleshooting',
      ],
    },
  ],
};

export default sidebars;
