/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package command-line-arguments */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 17 "main.go"

#include <stdlib.h>
#include <stdint.h>
#include <string.h>

typedef unsigned long long helm_sdkpy_handle;

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern char* helm_sdkpy_last_error();
extern void helm_sdkpy_free(void* ptr);
extern char* helm_sdkpy_version_string();
extern int helm_sdkpy_version_number();
extern int helm_sdkpy_config_create(char* namespace, char* kubeconfig, char* kubecontext, helm_sdkpy_handle* handle_out);
extern void helm_sdkpy_config_destroy(helm_sdkpy_handle handle);
extern int helm_sdkpy_install(helm_sdkpy_handle handle, char* release_name, char* chart_path, char* values_json, char* version, int create_namespace, int wait, int timeout_seconds, char** result_json);
extern int helm_sdkpy_upgrade(helm_sdkpy_handle handle, char* release_name, char* chart_path, char* values_json, char* version, char** result_json);
extern int helm_sdkpy_uninstall(helm_sdkpy_handle handle, char* release_name, int wait, int timeout_seconds, char** result_json);
extern int helm_sdkpy_list(helm_sdkpy_handle handle, int all, char** result_json);
extern int helm_sdkpy_status(helm_sdkpy_handle handle, char* release_name, char** result_json);
extern int helm_sdkpy_rollback(helm_sdkpy_handle handle, char* release_name, int revision, char** result_json);
extern int helm_sdkpy_get_values(helm_sdkpy_handle handle, char* release_name, int all_values, char** result_json);
extern int helm_sdkpy_history(helm_sdkpy_handle handle, char* release_name, char** result_json);
extern int helm_sdkpy_pull(helm_sdkpy_handle handle, char* chart_ref, char* dest_dir);
extern int helm_sdkpy_show_chart(helm_sdkpy_handle handle, char* chart_path, char** result_json);
extern int helm_sdkpy_show_values(helm_sdkpy_handle handle, char* chart_path, char** result_json);
extern int helm_sdkpy_test(helm_sdkpy_handle handle, char* release_name, char** result_json);
extern int helm_sdkpy_lint(helm_sdkpy_handle handle, char* chart_path, char** result_json);
extern int helm_sdkpy_package(helm_sdkpy_handle handle, char* chart_path, char* dest_dir, char** result_path);
extern int helm_sdkpy_repo_add(helm_sdkpy_handle handle, char* name, char* url, char* username, char* password, char* options_json);
extern int helm_sdkpy_repo_remove(helm_sdkpy_handle handle, char* name);
extern int helm_sdkpy_repo_list(helm_sdkpy_handle handle, char** result_json);
extern int helm_sdkpy_repo_update(helm_sdkpy_handle handle, char* name);

#ifdef __cplusplus
}
#endif
